### ISSUE TITLE
Book purchase link is dead in readme.

### ISSUE THREAD

**Issue by Kenneth-Sweet** [rswinkle/mips_book#1]
Hello, I'm working through your book and enjoying it, but unable to find where to purchase to show thanks and get answers to check my work, is this still available?

**Comment by rswinkle** [comment]
Yeah my Wordpress store crashed a few weeks ago and I haven't bothered to figure out how to fix it yet (I am not a web developer and even less of an IT/sysadmin type person).  It's on my TODO list but not super high priority since if you purchased the solutions you would only be the 3rd to do it since I released them early this year (I'm not a marketer/advertiser either).

In the meantime if you send me $5 (the "early bird" price when I optimistically released it) or the full $8 or more if you want to really show your support I can email you the zip file.  There are a few ways on my website [here](https://www.robertwinkler.com/donations.html) some that get your email at the same time.  Or you can just send me the money and your email in the note via [Cash App](https://cash.app/$robwink).

Did you see the book specific email address on the main page/README and at the top and Info section of the book?   Not that contacting me here in an issue doesn't work, I'm just wondering if I should make it that email more prominent or put it somewhere else if you didn't see it.

Any critiques/typos?  Are you reading it for a class or just for fun?  Have a good night.

**Comment by Kenneth-Sweet** [comment]
Thanks for the response, I definitely see the email on your book now, and probably should've caught that I would think that's more a user issue than needing to be more prominent. Sent my email via cashapp.

I'm currently trying to get into reverse engineering PSX games and want to get a foundation in MIPS and C and ran into your book. Your book has hands on c to asm translation exercise which should mirror what I'll be doing(huzzah!).

So far no issues(only through chapter 2) but I'll be sure to point out any if I do!

**Comment by rswinkle** [comment]
Looks like I forgot to close this.

Hope you found the rest of the book useful and succeeded in your PSX reverse engineering goals.
